## YAML Template.
---
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mundialdb
        username: root
        password:
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
        show-sql: true